### ISSUE TITLE
Replace `vec_clone()` with the STL functions 

### ISSUE THREAD

**Issue by IvanaGyro** [Cytnx-dev/Cytnx#459]
[vec_clone](https://github.com/Cytnx-dev/Cytnx/blob/fa4596e1620cc304f698286905818a2118b2bd8e/include/utils/vec_clone.hpp#L4) without given `locators` does the same thing with `std::copy`, `vector` assignment, or `vector` initialization. The cases given `locators` can be replaced with `std::transform`.

**Comment by kaihsin** [comment]
Is this specifically for implementation or you are thinking remove this API

**Comment by IvanaGyro** [comment]
We don't export `vec_clone`, do we? This issue proposes to remove the definition of `vec_clone` from the code base. More precisely, remove `vec_clone.hpp` and `vec_clone.cpp` and update all code referring to this function.

**Comment by kaihsin** [comment]
We do. It's part of the C++ API, which we provide some syntax sugar for
user.

--Kai

**Comment by IvanaGyro** [comment]
Where can I see all the APIs?

**Comment by kaihsin** [comment]
Look at headers in includes/. All the internal API headers are inside src/

**Comment by kaihsin** [comment]
Basically all the API in include/cytnx.h are public facing

**Comment by IvanaGyro** [comment]
I see. I think it's okay to remove the API because `vec_clone` is covered by the STL. Usually, people want to use STL as much as possible.

**Comment by kaihsin** [comment]
unfortunately you can't because vec_clone does not only apply to built-in types it also apply to Tensor, UniTensor, Bond... second class. 

Specifically, the reason to have this API is 
It has special behave than STL. It will check the Nelem, and does not call the copy constructor (it actually call clone(), which is not nessasry the same as just copy the whole class mem like STL does)

**Comment by IvanaGyro** [comment]
I see, I didn't notice that. However, it will be more intuitive to implement the copy constructor to do a deep copy. The purpose of the current copy constructors can be achieved by passing as references. This will make cytnx's classes interact with STL better. Let's leave `vec_clone` now. 

```cpp
Tensor& new_ref = old_ref_to_tensor;
void foo(Tensor& input_tensor);
```

**Comment by kaihsin** [comment]
Actually, the point is to NOT doing that. As I mentioned, Cytnx C++ API is
intentionally designed to be not behave like C++ but more like python.

Copy constructor is definitely the thing we DONT want to do. That's the
core of why we need a .clone() to do a copy operation.

Everything is referenced

**Comment by IvanaGyro** [comment]
The design spirit is great. However, C++ and Python have different typing systems. Making copy constructors as shadow copy and erasing the type of each class lose huge benefits of type checking from the compiler, which we check the type manually at runtime, and of compatibility with STL. If users want to put cytnx's classes into STL containers, they may get pain and try to wrap cytnx's into STL-like classes. If there will be a discussion about this while refactoring, that will be great.

**Comment by ianmccul** [comment]
I agree with Ivana -- the reference binding semantics of Python are probably the most confusing aspect of the language, and replicating that with C++ just makes the C++ code confusing, non-ideomatic C++ that is incompatible with a lot of standard algorithms.  Eg, `std::swap()` won't work with a `Tensor`, so you can't put them in a container and call `std::sort` or `random_shuffle` etc.

In practice, a Python object is something like a `shared_ptr<T>`, which of course you could do in C++ if you wanted, but often you just want a T.  If it is really useful enough to have reference semantics in C++ then it is best to name it differently, eg as a `TensorRef`.

In my code there is still quite a bit of reference counting, but that is left over from before move semantics even existed, but even then it has copy-on-write (value) semantics.  I briefly had some objects using reference semantics, but I got rid of them because it was too confusing.  The reasons for using reference counting in C++ have almost entirely gone with move semantics and mandatory RVO and copy elision, and requires careful treating with mult-threading, so I'd avoid it if possible.

**Comment by kaihsin** [comment]
Actually, std:swap will work for Tensor, they are still compatible with STL
calls. Think about it as a trivial wrapper class that has a pointer. When
we say A=B, A and B share the same pointer, but the wrapper class object is
different. By doing so, STL operation will still work, in the sense that it
doesn't cause any trouble at all for most of the STD algorithms

**Comment by ianmccul** [comment]
Right, I realized that later.  Still, the semantics are rather non-ideomatic C++, in that you have no way of knowing which objects are aliasing other objects. eg you could have a container that has multiple references to the same object.

**Comment by kaihsin** [comment]
That's exactly the point for minimizing memory movement.

One good example is permute. You want to be able to delay the copy and
memory movement until you hit the actual o.p. point.

A trivial example is like:

B = C.permute(3,1,2).permute(2,1,3)
B*A

The memory movement only need to happen once when B*A instead of Everytime
you call permute you move memory. I believe the benefit of this from the
numpy/pytorch's experience goes without saying. Not to mention once you
have AD you need to even keep track of the whole call graph. Then in this
sense the most efficient and hassle free solution is to do default ref and
explicitly copy

**Comment by kaihsin** [comment]
But that being said, yes, there will be performance overhead, but
considering most of the complexity is usually from memory operation and
linalg. The part that you really want to squeeze out from python is usually
for loop and some complicated meta analysis (which it's considered as
internal stuff, then we use C++ class instead of public API class anyway)

**Comment by kaihsin** [comment]
This is a great discussion!

For that code,
C.permute return a new C++ class (with different meta data), but with
shared memory with B ( its a bit more complicated than that cauz we did ref
counting for garbage collect and also mutithread guard under the hood but
anyway :) )  so it is NOT modifying memory inplace. And the actual moving
of memory is done at the point where the operator* is called.

Actually the whole point is to do it such that  everytime you do permute,
you don't recalculate the change of elements, but simply record the change
as meta either by a graph or some sort of meta data structure. , and then
it's only at certain "choking point operation"(such as explicitly call
contiguous(), contraction, linalg ops...) when you apply change to
elements/internal data structures.

Iiuc (plz correct me if I am wrong!) but for non-abelian you can always
write down a abstract fusion tree as a meta data, and permutation are
simply manip this tree

**Comment by ianmccul** [comment]
Yes absolutely, using reference counting to avoid making copies, and just changing the metadata is a good thing to do.  In my new design for the tensors (which is actually something I had in my really old code, circa 1998), this 'metadata' includes a scalar factor, so you can even multiply by scalar, normalize, etc as O(1) operations.  With non-abelian symmetries this is very useful because basically every operation has some coupling coefficient, and BLAS has these scalar factors anyway so there is no loss of efficiency[*].

For non-abelian symmetries, whenever you do something that affects the fusion tree, there is a 6j transformation that can mix up different blocks. So some blocks of the final tensor might be able to re-use the storage, other blocks will need to do a basis transformation and allocate new memory.  So value-semantics reference counting is the obvious way to do this, so it transparently re-uses memory where possible.  But from the user perspective it is an implementation detail - it would work in exactly the same way as if it just copied everything.

For Python code, reusing the underlying storage but with changed metadata, something like a 'view' of the data, is rather un-Pythonic.  Modern python favors immutability and clear side-effects.  I think the example above, even in Python, where B could be modified via C, is unexpected.  But I'm not really a Python programmer, I think it would be good to get a viewpoint from the TenPy people on this!  But in any event, I think such semantics are not possible with non-abelian symmetries.

[*] well in some sense there is, since BLAS will special-case when the scalar factor is 1, but that is just moving the multiplication factor into BLAS, where it will be faster than doing it yourself.

**Comment by IvanaGyro** [comment]
I think whether the copy construct does the job of the move constructor or not, we can always fully manage the memory, for example doing permutation in-place,  as we want in C++. For the case in the example 

```
B = C.permute(3,1,2).permute(2,1,3)
D = B*A;
```

Whether B is a reference to C depends on the implementation of `permute()`. It's independent of type erasing and the design of the copy constructor.

**Comment by kaihsin** [comment]
Which copy constructor are you referring to here? (By means of copy I
actually means copy operation in general, including assignments)

For example,

How do you say the behavior of
B=C should be? Should it copy the memory?

I am not actually not sure how much drawback it will be from type erasing.
There is not much to optimize with a specific type. If we were doing a type
dispatch by pattern matching then I agree runtime doing this is super
expensive. But we are doing actual dynamical dispatch approach, there is no
switch, no if else involves. Then in this sense I am not sure it will cause
issues.

Tbh, C++ copy semantics are always the most confusing one for me, because
the fact that you can overload copy constructor/assignments. Then it
literally have no universal expectations on what a behavior should actually
be...

Regarding to Ian's concern about modify B will affect C, this is actually
easy to solve (if we really want to restrict the behavior) we can guard the
set element to only allow write when there is only single ref (yes, we
separate the get and set element so it does not just rely on one pointer
lval). But I believe there are use case for it.

**Comment by kaihsin** [comment]
https://discourse.julialang.org/t/what-is-the-philosophy-behind-arrays-not-being-copied-when-assigned-to-another-variable/98702/3

**Comment by ianmccul** [comment]
> How do you say the behavior of B=C should be? Should it copy the memory?

In Python, it depends on whether C is immutable or not.  If it is immutable, then it makes a copy (or at least conceptually it does; maybe it uses copy-on-write reference counting, but for the user it doesn't matter).  If it is not immutable then it doesn't copy, and modifying B will also change C.

But this is not the idiomatic C++ way.   The description in the Julia discourse is I think a bit unfair to C++.  It is true that you can overload the copy-assignment and copy-constructors in C++ to do whatever you want, but the standard expectation is that objects will have value semantics, so that user-defined objects behave as closely as possible to builtin types.  This is true also of pointers, and eg shared_ptr.  The pointer is itself a value, and assignment of a pointer copies that value.  If you have a C++ object that has other semantics, then you should make very clear what the semantics are.  Eg I have a `MatrixRef`, which acts as a reference to some other matrix (it behaves similarly to a `Matrix&`).  The standard `Matrix` has value semantics (although behind the scenes it is using copy-on-write reference counting, that is an implementation detail).

> Regarding to Ian's concern about modify B will affect C, this is actually easy to solve (if we really want to restrict the behavior) we can guard the set element to only allow write when there is only single ref (yes, we separate the get and set element so it does not just rely on one pointer lval). But I believe there are use case for it.

If you are going to do that, then you might as well just do copy-on-write.  All it means in practice is that instead of throwing an exception at runtime if there is more than one reference, then do a deep copy.

If you are going to share memory in non-trivial ways, eg so code like
`
B = C.permute(3,1,2).permute(2,1,3)
`
allows changes in B to affect C in non-trivial ways, then it is best done in C++ using some kind of 'view' type.  Eg
`
TensorPermuteView B = Permute(C,3,1,2);
B(i,j,k) = 5;  // also changes C(k,i,j)
`

Python seems inconsistent on this.  Eg the documentation for [Numpy.transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) says 'A view is returned whenever possible.'.  I don't see how you could make use of this in practice, to actually modify the elements of an array via a view to its transpose, if it isn't guaranteed to actually happen.  On the other hand, if you want to guarantee that the transpose is actually a different object, then you need to `copy()` it just to make sure.  That doesn't seem sensible to me; it should either return a view, or return a copy (which doesn't need to be an actual copy, if it uses copy-on-write reference counting).

**Comment by kaihsin** [comment]
I think it really depends on what ppl we want to serve.  Most user don't
really bother using the C++ API. They usually come from python, and then
want to leverage a few key components from C++ to speed things up.

I think C++ is flexible enough so that you can do anything providing the
C++ semantics allows you to do it.

Pytorch is already doing this on their C++ API. Our implementation is
really nothing special but following their convention.

And considering many projects build on it, I don't see why we cannot do it.
In fact it makes integration to pytorch and other library easier.

**Comment by ianmccul** [comment]
> Iiuc (plz correct me if I am wrong!) but for non-abelian you can always write down a abstract fusion tree as a meta data, and permutation are simply manip this tree

No, this is not correct.  Permutations are a non-trivial basis change.  In some cases this might just be a scalar factor, eg
```
 \
  \
  /\
 i  \
    /\
   j  \
       \
        k
```
if you swap j and k legs here, there is a phase factor (and maybe more than that, for some cases? I'm not sure).  Eg, for SU(2), if j and k are both spin-1/2 then there is a -1 sign.  This arises from the symmetries of the clebsch-gordan coefficients.

This is ignoring braiding, which is another level. If you are actually braiding those indices, then you need the R-matrix.  This is probably the physical operation that you mean here.  So if it is fermions for example, then there is a -1 phase from the swap operation. This is in addition to the factor from the 6j coefficient above, so eg even for a spin chain, treating the spins as bosonic statistics, there is still a -1 phase above, and if your spins are fermions then there is another -1from the fermion statistics. For non-abelian anyons, it can do some non-trivial mixing.  I.e. R(j,k) is not necessarily a diagonal matrix. I guess this could be stored as metadata, but I am not sure how to do that efficiently. Maybe there is a way, do you know of any non-abelian tensor libraries that do this?

If you want to permute two indices that are not adjacent in the fusion tree, then you need to first do F-moves so that they are adjacent.  For a non-abelian symmetry this is a non-trivial operation that is not diagonal in the indices and changes the internal labels.

You need to do this for operations other than permutation as well, eg for some a contraction you might need to rearrange the fusion trees so that they are compatible and the indices are adjacent (which involves F-moves but not braiding).

**Comment by kaihsin** [comment]
The only existing one I know is this one from Jutho:

https://jutho.github.io/TensorKit.jl/stable/

--Kai

**Comment by ianmccul** [comment]
> I think it really depends on what ppl we want to serve.  Most user don't really bother using the C++ API. They usually come from python, and then want to leverage a few key components from C++ to speed things up.

Right, if everyone is just using Python anyway, then the semantics of the C++ interface don't really matter much.  I don't know much PyTorch, but I was just browsing the C++ interface, and it looks like it would be quite annoying to use in a pure C++ project.  It would end up as python-like code but with C++ syntax.  Maybe that is what people want...  Personally, I find the idea that it is **unspecified** whether some operation makes a copy versus returning a 'view' to be rather abhorrent!

**Comment by ianmccul** [comment]
> The only existing one I know is this one from Jutho: https://jutho.github.io/TensorKit.jl/stable/

Yeah, my guess is that is probably the 'state of the art', with respect to the amount of thought put into it.  I haven't looked closely at it, I should one day ...

There are a few other libraries that do non-abelian tensors though, I listed a few in my email last night, and I expect that there are others that I don't know about.

**Comment by ianmccul** [comment]
I've been looking a bit at the TensorKit documentation.  When permuting indices, it only avoids a copy in the case where `sectortype(S) == Trivial` i.e. when there are no symmetries at all.
