### ISSUE TITLE
QR decomposition with LinearOperator

### ISSUE THREAD

**Issue by manuschneider** [Cytnx-dev/Cytnx#499]
For a CTMRG algorithm I need  `linalg.Qr` with a linear operator as an input instead of a `Tensor` or a `UniTensor`. This is crucial for the runtime.
Currently, only `Arnoldi` and `Lanczos` (in different flavours) work with `LinOp` as an input argument. `Qr`, `Svd` etc do not.

**Comment by ianmccul** [comment]
QR decomposition is normally used with dense matrices.  `LinOp` only provides access to the matrix-vector multiply, so it would need to be some iterative/sparse QR.  There are sparse methods that store Q as a product of Givens rotations, rather than constructing an explicit matrix.  This would work by successively removing elements of the sparse matrix that are below the diagonal, and accumulating the sequence of Givens rotations that can be used to reconstruct Q.  It isn't clear to me how this could be done on a matrix that has internal contractions.

**Comment by yingjerkao** [comment]
> For a CTMRG algorithm I need `linalg.Qr` with a linear operator as an input instead of a `Tensor` or a `UniTensor`. This is crucial for the runtime. Currently, only `Arnoldi` and `Lanczos` (in different flavours) work with `LinOp` as an input argument. `Qr`, `Svd` etc do not.

Here is a CTM implementation using Cytnx: https://github.com/Cytnx-dev/Cytnx_ctmrg

I do not quite understand why you need to put a linear Operator to QR in CTM. Isn't QR is just for the projector calculation?

**Comment by manuschneider** [comment]
Thanks for the comments, you are absolutely right. The QR typically needs the full matrix. Or in other words, even if a matrix-vector multiplication `M v` can be implemented efficiently, it would be called n times in the QR decomposition for an (n x n) input matrix `M`. So there is no way to make things more efficient with `LinOp` for the usual QR.
`LinOp` is of course only useful if a few eigenvalues / singular values are needed.
