### ISSUE TITLE
Consider not to use OMP for `FillCpu()`

### ISSUE THREAD

**Issue by IvanaGyro** [Cytnx-dev/Cytnx#511]
The job of `FillCpu()` is to fill a range with the given value. We only support the arithmetic types and `std::complex` now, so the cost for assigning each value is low. Parallelizing the for loop may take longer time comparing with running the function on a single thread. The result and the code for benchmarking are put at the bottom. Running on the single thread is faster in the most of cases. However, there are some concerns:

1. May impact the performance on HPC (I don't have any experience with HPC).
2. Parallelizing with OMP may be faster if we support big integer or other bigger types.

Welcome to leave comments.

benchmark results:
```
Input count:1000000
Type:i Count:1000000
Total time for FillCpuNoOmp: 0.000766937 seconds
Total time for FillCpu: 0.212465 seconds

Type:d Count:1000000
Total time for FillCpuNoOmp: 0.000890001 seconds
Total time for FillCpu: 0.391436 seconds

Type:St7complexIdE Count:1000000  ------> std::complex<double>
Total time for FillCpuNoOmp: 4.36671 seconds
Total time for FillCpu: 3.56453 seconds --------> OMP wins

Input count:10000000   
Type:i Count:10000000
Total time for FillCpuNoOmp: 0.00476153 seconds
Total time for FillCpu: 20.0611 seconds

Type:d Count:10000000
Total time for FillCpuNoOmp: 0.00633429 seconds
Total time for FillCpu: 45.7951 seconds

Type:St7complexIdE Count:10000000
Total time for FillCpuNoOmp: 43.7523 seconds
Total time for FillCpu: 96.3701 seconds
```

```cpp
/** compile command: g++ -std=c++17 -fopenmp -O3 -o fill.o fill.cpp && ./fill.o */

#include <iostream>
#include <chrono>
#include <omp.h>
#include <complex>

using namespace std;

template <typename DType>
void FillCpu(void *first, const DType &value, size_t count) {
  DType *typed_first = reinterpret_cast<DType *>(first);
#pragma omp parallel for schedule(static)

  for (int i = 0; i < count; ++i) {
    typed_first[i] = value;
  }
}

template <typename DType>
void FillCpuNoOmp(void *first, const DType &value, size_t count) {
  DType *typed_first = reinterpret_cast<DType *>(first);
  for (int i = 0; i < count; ++i) {
    typed_first[i] = value;
  }
}

template <typename DType>
void BenchmarkFill(int count) {
  int num_iterations = 10000;
  DType *ptr = reinterpret_cast<DType *>(malloc(sizeof(DType) * count));
  DType value(10);
  cout << "Type:" << typeid(DType).name() << " Count:" << count << "\n";
  {
    auto start = chrono::high_resolution_clock::now();
    for (int iter = 0; iter < num_iterations; ++iter) {
      FillCpuNoOmp(reinterpret_cast<void *>(ptr), value, count);
    }
    auto end = chrono::high_resolution_clock::now();
    const std::chrono::duration<double> total_time = end - start;
    cout << "Total time for FillCpuNoOmp: " << total_time.count() << " seconds\n";
  }

  {
    auto start = chrono::high_resolution_clock::now();
    for (int iter = 0; iter < num_iterations; ++iter) {
      FillCpu(reinterpret_cast<void *>(ptr), value, count);
    }
    auto end = chrono::high_resolution_clock::now();
    const std::chrono::duration<double> total_time = end - start;
    cout << "Total time for FillCpu: " << total_time.count() << " seconds\n";
  }
  cout << "\n";
}

int main() {
  int count;
  cout << "Input count:";
  cin >> count;
  BenchmarkFill<int>(count);
  BenchmarkFill<double>(count);
  BenchmarkFill<complex<double>>(count);
}

```

**Comment by ianmccul** [comment]
This is a copy of a comment I made on the PR #508 , but buried in the code discussion.

Dynamic scheduling is only useful when the execution time of each iteration in the loop will vary, and you want to avoid the situation where some threads have finished their work, but there is one thread still running (and therefore blocking everything else).  But what kills the performance of the dynamic scheduling benchmark is that the default chunk size (the number of elements of the array processed at a time) is 1, for dynamic scheduling.  So each thread is only processing one element at a time.  If you specify a sensible chunk size, say 1000000, then dynamic scheduling will be basically indistinguishable from static scheduling here.  But of course there is no reason to use dynamic scheduling anyway.

I am slightly surprised that you see a benefit from OpenMP here at all actually - setting an array of memory to some value is going to be purely memory bandwidth limited.  A single thread can saturate the memory bandwidth on a modern CPU.  I modified the benchmark to add a non-OpenMP version - I also needed the `DoNotOptimize()` function because at -O3 the compiler was completely optimizing away the loop!  This shows that if the array size is small enough to fit inside the L3 cache (about 16 MB typically), then OpenMP tops out at a bit under a factor 2 faster, so probably useful.  But that is not the common case - it depends on having the array already in the cache.  For array sizes larger than the L3 cache, there is about 30% improvement with 4 threads - using more gets slower again, presumably the threads are fighting each other for memory bandwidth.  I think an optimized single-thread copy, that uses SIMD instructions, would be best here.  Surprisingly, I wasn't able to get gcc to make a SIMD-vectorized loop, not sure what I was doing wrong.

In summary, static omp with a small number of threads is slightly useful, but I suspect a SIMD optimized version would be better still.  I can't imagine any situation where the benefit from using openmp here is noticable in a realistic code.  Initializing memory to 0 is a special case that is worth treating separately, and `memset` will likely be faster than any openmp solution.

The benchmarks:
| Array size | Threads | CPU (ms) | omp-static (ms) | omp-dynamic (ms) |
| -- | -- | -- | -- | -- |
| 10'000'000 (< L3 cache) | 1 | 2.40328 | 2.41689 | 2.38274 |
| 10000000         | 2 | 2.53097 | 2.06814 | 2.05014  |
| 10000000         | 4 | 2.40613 | 1.67919 | 1.59296 |
| 100'000'000 (> L3 cache) | 1 | 32.6479 | 31.8224 | 33.9212 |
| 100'000'000  | 2 | 33.2148 | 29.2628 | 28.9037 |
| 100'000'000  | 4 | 33.7245 | 21.7398 | 22.4597 |

The code:
```c++
// compile command: g++ -std=c++17 -fopenmp -O3 -o fill fill.cpp && ./fill 1000000 4

#include <iostream>
#include <chrono>
#include <cstdlib>
#include <omp.h>

using namespace std;

// from https://github.com/google/benchmark/blob/62a321d6dc377e0ba9c712b6a8d64360616de564/include/benchmark/benchmark.h#L525
template <typename Tp>
inline void DoNotOptimize(Tp const& value) {
  asm volatile("" : : "r,m"(value) : "memory");
}


template <typename DType>
void FillCpu(void *first, DType value, size_t count) {
  DType *typed_first = reinterpret_cast<DType *>(first);
  for (int i = 0; i < count; ++i) {
    typed_first[i] = value;
  }
}

template <typename DType>
void FillCpuStatic(void *first, const DType &value, size_t count) {
   DType *typed_first = reinterpret_cast<DType *>(first);
   #pragma omp parallel for schedule(static)
   for (int i = 0; i < count; ++i) {
      typed_first[i] = value;
   }
}

template <typename DType>
void FillCpuDynamic(void *first, const DType &value, size_t count) {
  DType *typed_first = reinterpret_cast<DType *>(first);
#pragma omp parallel for schedule(dynamic,1000000)
  for (int i = 0; i < count; ++i) {
    typed_first[i] = value;
  }
}

int main(int argc, char** argv) {
  if (argc < 3) {
    cout << "expected: fill <count> <threads>\n";
    return 1;
  }
  int count = atoi(argv[1]);
  int nthreads = atoi(argv[2]);
  omp_set_num_threads(nthreads);
  int num_iterations = 10'000'000'000ll / count;
  cout << "Using " << num_iterations << " iterations." << endl;
  int *ptr = reinterpret_cast<int *>(malloc(sizeof(int) * count));
  int value = 10;

  {
    auto start = chrono::high_resolution_clock::now();
    for (int iter = 0; iter < num_iterations; ++iter) {
      FillCpu(reinterpret_cast<void *>(ptr), value, count);
      DoNotOptimize(ptr[0]);
    }
    auto end = chrono::high_resolution_clock::now();
    const std::chrono::duration<double> total_time = end - start;
    cout << "Total time for FillCpu: " << (total_time.count()*1000/num_iterations) << " milliseconds" << endl;
  }

  {
    auto start = chrono::high_resolution_clock::now();
    for (int iter = 0; iter < num_iterations; ++iter) {
      FillCpuStatic(reinterpret_cast<void *>(ptr), value, count);
      DoNotOptimize(ptr[0]);
    }
    auto end = chrono::high_resolution_clock::now();
    const std::chrono::duration<double> total_time = end - start;
    cout << "Total time for FillCpuStatic: " << (total_time.count()*1000/num_iterations) << " milliseconds" << endl;
  }

  {
    auto start = chrono::high_resolution_clock::now();
    for (int iter = 0; iter < num_iterations; ++iter) {
      FillCpuDynamic(reinterpret_cast<void *>(ptr), value, count);
      DoNotOptimize(ptr[0]);
    }
    auto end = chrono::high_resolution_clock::now();
    const std::chrono::duration<double> total_time = end - start;
    cout << "Total time for FillCpuDynamic: " << (total_time.count()*1000/num_iterations) << " milliseconds" << endl;
  }
}
```

**Comment by ianmccul** [comment]
https://github.com/Cytnx-dev/Cytnx/blob/e2b00f0abd2ab9869973c810ddb8ed8b949460c3/src/backend/utils_internal_cpu/Fill_cpu.hpp#L27

Please (please please!) change the signature of this function to

```c++
template <typename DType>
    void FillCpu(DType *first, DType value, cytnx_uint64 count)
```
The most important change is to pass the array pointer as properly typed.  As written, the function fills an untyped array with whatever type is in `value`.  The function has no way of knowing whether the type is correct or not before doing the dangerous `reinterpret_cast`.  The caller of the function should be responsible for getting the type of the array correct.

The second change is to pass the `value` parameter by value.  There is no reason for a reference here, and it will inhibit optimizations.  The reason is that the compiler has no way of knowing whether `value` refers to an element in the array or not.  A smart compiler could figure out that even if `value` is in the array then it makes no difference for this particular function, but I tested it on godbolt and with a reference parameter it loads it again every time through the loop.  The only reason it isn't a factor 2x slower is speculative execution and `&value` will be in the L1 cache.  To see why this happens, consider a slightly different function:

```c++
void add_value(int* first, int count, const int& value) {
   for (int i = 0; i < count; ++i) {
      first[i] += value;
   }
}
```

Now consider what happens if we have
```c++
int main() {
   std::vector<int> v(20, 1);
   add_value(v.data(), v[10]);
   for (auto x : v)
      cout << x << ' ';
}
```
The output is `2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3`.

**Comment by ianmccul** [comment]
By the way, what will be happening in your benchmark is that in the no-OMP version, the compiler is noticing that the array is never used and optimizing away the loop.  The only time that doesn't happen is using `std::complex`, which, as a class type, the compiler cannot optimize as easily.  

A minimal fix gives:
Input count:1000000
Type:i Count:1000000
Total time for FillCpuNoOmp: 1.40522 seconds
Total time for FillCpu: 0.342093 seconds

Type:d Count:1000000
Total time for FillCpuNoOmp: 1.86324 seconds
Total time for FillCpu: 0.788924 seconds

Type:St7complexIdE Count:1000000
Total time for FillCpuNoOmp: 4.61312 seconds
Total time for FillCpu: 1.26059 seconds


```c++
/** compile command: g++ -std=c++17 -fopenmp -O3 -o fill fill.cpp && ./fill */

#include <iostream>
#include <chrono>
#include <omp.h>
#include <complex>

using namespace std;

// from https://github.com/google/benchmark/blob/62a321d6dc377e0ba9c712b6a8d64360616de564/include/benchmark/benchmark.h#L525
template <typename Tp>
inline void DoNotOptimize(Tp const& value) {
  asm volatile("" : : "r,m"(value) : "memory");
}

template <typename DType>
void FillCpu(void *first, const DType &value, size_t count) {
  DType *typed_first = reinterpret_cast<DType *>(first);
#pragma omp parallel for schedule(static)

  for (int i = 0; i < count; ++i) {
    typed_first[i] = value;
  }
}

template <typename DType>
void FillCpuNoOmp(void *first, const DType &value, size_t count) {
  DType *typed_first = reinterpret_cast<DType *>(first);
  for (int i = 0; i < count; ++i) {
    typed_first[i] = value;
    DoNotOptimize(typed_first[i]);
  }
}

template <typename DType>
void BenchmarkFill(int count) {
  int num_iterations = 10000;
  DType *ptr = reinterpret_cast<DType *>(malloc(sizeof(DType) * count));
  DType value(10);
  cout << "Type:" << typeid(DType).name() << " Count:" << count << "\n";
  {
    auto start = chrono::high_resolution_clock::now();
    for (int iter = 0; iter < num_iterations; ++iter) {
      FillCpuNoOmp(reinterpret_cast<void *>(ptr), value, count);
    }
    auto end = chrono::high_resolution_clock::now();
    const std::chrono::duration<double> total_time = end - start;
    cout << "Total time for FillCpuNoOmp: " << total_time.count() << " seconds\n";
  }

  {
    auto start = chrono::high_resolution_clock::now();
    for (int iter = 0; iter < num_iterations; ++iter) {
      FillCpu(reinterpret_cast<void *>(ptr), value, count);
    }
    auto end = chrono::high_resolution_clock::now();
    const std::chrono::duration<double> total_time = end - start;
    cout << "Total time for FillCpu: " << total_time.count() << " seconds\n";
  }
  cout << "\n";
}

int main() {
  int count;
  cout << "Input count:";
  cin >> count;
  BenchmarkFill<int>(count);
  BenchmarkFill<double>(count);
  BenchmarkFill<complex<double>>(count);
}
```

**Comment by yingjerkao** [comment]
Another possibility is to replace `void*` with `std::any`.

**Comment by IvanaGyro** [comment]
@ianmccul  
>The second change is to pass the value parameter by value. There is no reason for a reference here (...)

`fill` is different from `add_value`. The program is well-form even if the reference pointing an element in the range. For the algorithm that the assigned value cannot in the range, we can refer to [std::replace](https://en.cppreference.com/w/cpp/algorithm/replace)

> Because the algorithm takes old_value and new_value by reference, it can have unexpected behavior if either is a reference to an element of the range [first, last). 

It seems the caller should take the responsibility to check if the given value is refer to the element in the range or not in STL.

For parallel computing, I recommend use built-in parallel algorithms and execution policies if it's possible. There is [a table](https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features) shows how this feature is supported by the compilers. GCC requires TBB to support parallel algorithms and Clang support [some important algorithms](https://libcxx.llvm.org/Status/PSTL.html).

Managing data in Storage by `std::vector` or `thurst::vector` is planned. After finish the job, we can just drop `FillCpu()` and use `std::fill_n` instead.

**Comment by IvanaGyro** [comment]
Let's trace the issue about OMP in #517.

**Comment by ianmccul** [comment]
> @ianmccul
> 
> > The second change is to pass the value parameter by value. There is no reason for a reference here (...)
> 
> `fill` is different from `add_value`. The program is well-form even if the reference points to an element in the range. 

I agree it is well-formed and behaves properly.  The point is that DType is normally going to be something very small, that will most likely fit in a register (or two registers, in the case of complex).  There is no reason to ever pass such a parameter by const reference.  `int` is 4 bytes, a pointer is 8 bytes, but even for a `complex<double>` (16 bytes) it will be usually be faster to pass by value. But in this case, it also inhibits compiler optimization because it needs to re-load the memory location of &value every time through the loop.  Consider [this code on godbolt](https://godbolt.org/z/qrWq5exvq):

```c++
void FillReference(int* first, int count, const int& v) {
    for (int i = 0; i < count; ++i)
    {
        first[i] = v;
    }
}
```
The key part of the generated assembly code is this fragment:
```assembly
.L3:
        mov     eax, DWORD PTR [rdx]
        add     rdi, 4
        mov     DWORD PTR [rdi-4], eax
        cmp     rdi, rcx
        jne     .L3
```
Translating this into pseudo-code: (I swapped lines 2 and 3: for some reason the code is incrementing the index by 4 and then referring to array[index-4], but it is equivalent code)

1. LOAD *(&v) from memory into register EAX
2. SAVE EAX into the current array memory location
3. ADD 4 bytes to the array location
4. COMPARE if we have reached the end of the array
5. IF we are not yet at the end of the array, then jump back to step 1

The key point is step 1 of the loop: it is loading the memory location of &value into a register every time through the loop.  It must do this, because it has no idea what is happening in the rest of the program.  For example, if another thread changed the contents of v.  **Most** of the time, this load will be very fast: it will be in the L1 cache, and the CPU might even speculatively assume that the memory location hasn't changed.  But it could certainly be the case that another thread accesses the same cache-line as &v, and that will cause a `speed bump` as the CPU will have to stop and fetch the memory location out-of-cache again.

Compare with the corresponding code when passing by value:
```c++
void FillValue(int* first, int count, int v) {
    for (int i = 0; i < count; ++i)
    {
        first[i] = v;
    }
}
```
The generated assembly for the loop is:
```assembly
.L8:
        mov     DWORD PTR [rdi], edx
        add     rdi, 4
        cmp     rdi, rax
        jne     .L8
```

The loop is only 4 instructions rather than 5, and importantly there is only one instruction that references memory.  In pseudocode this is:

1. SAVE EAX into the current array location
2. ADD 4 bytes to the array memory location
3. COMPARE if we have reached the end of the array
4. IF we are not yet at the end of the array, then jump back to step 1

Interestingly, if you compile this with `-O3`, then the compiler does something very clever.  It turns `FillReference()` into the equivalent of:
```c++
void FillReference(int* first, int count, const int& v) {
    // check and see if &v is outside the array.  If so, then optimize the loop
    if (&v < first || &v > (first+count)) {
        FillValue(first, count, v);
    } else {  // slow path -- load v from memory
        for (int i = 0; i < count; ++i)
        {
            first[i] = v;
        }
    }
}
```


See also https://medium.com/@lucianoalmeida1/back-to-basics-pass-by-value-vs-pass-by-ref-96a591c88174 which I just found on google, that discusses these issues more - there is a similar example at the end.
   
> For the algorithm that the assigned value cannot in the range, we can refer to [std::replace](https://en.cppreference.com/w/cpp/algorithm/replace)
> 
> > Because the algorithm takes old_value and new_value by reference, it can have unexpected behavior if either is a reference to an element of the range [first, last).

Yes, this is a limitation throughout much of the STL.  `replace` pre-dates *move* semantics in C++, so when it was designed there was no choice but to pass the parameter by reference, because it cannot assume that T has a copy constructor.  It is not a good model to follow for high performance code. The issue in general is referred to as *aliasing*, and it is a big problem in languages like C/C++.

As an aside, this is mainly where Fortran gets its reputation for being fast, because the language forbids aliasing.  C added the **restrict** keyword to try to manage this, but it never caught on, I think it is just too difficult to use.  But the idea would be, if it was added to C++, then you could write `void FillReference(int* first, int count, const int& restrict v)`, and this is telling the compiler that `v` is not aliased with anything else, and the compiler could treat `FillReference()` the same as `FillValue()`.

> 
> It seems the caller should take the responsibility to check if the given value is refer to the element in the range or not in STL.

Yes, this is a design limitation of the STL.  From the perspective of calling an STL algorithm, it is best to consider it as **undefined behavior** to call algorithms in that way, although from C++ language perspective it is well-defined, but just not likely to behave how the programmer expected.

> For parallel computing, I recommend use built-in parallel algorithms and execution policies if it's possible. There is [a table](https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features) shows how this feature is supported by the compilers. GCC requires TBB to support parallel algorithms and Clang support [some important algorithms](https://libcxx.llvm.org/Status/PSTL.html).

This is actually a bad idea, at least for the time being.  Maybe in the future, C++26 or beyond.  But the C++17 parallel algorithms are not usable for HPC.  I remember reading a very good paper from some numerics guys at Sandia (I think?!) that discusses this in detail, but I cannot find it now.  The bottom line is that the C++17 parallel algorithms don't give enough control over the execution environment, and introduce bottlenecks.  This was largely the motivation for a bunch of numerics people to get onto the C++ standards committee to fix this!  And what led to `std::mdspan` in C++23, and some major improvements to the parallel algorithms.  So maybe in 10 years time...

I did find (this article from ACCU) [https://accu.org/journals/overload/29/161/teodorescu/] .  I have only skimmed it, but it looks like it covers most of the important problems. From the conclusion of that article:
> C++ parallel algorithms bring vectorisation to common algorithms, without requiring a lot of effort from the user. This is great! C++ parallel algorithms also bring parallel versions of the algorithms without requiring a lot of effort from the user. However, this is not that great. It is a tool that can be useful in some cases, but it’s not great.
>
> First, there is a central design issue. Moving to multicore programming requires a somehow-global concurrency design. C++ parallel algorithms don’t offer any support for this. Moreover, the standard sends a bad signal to all the C++ programmers that somehow parallelism can be achieved without concurrent thinking. I can’t stress enough how bad is this.
> [...]
> All these make C++ parallel algorithms not such a great addition in the concurrency toolkit. They are ok, they are needed, but it’s still not enough. I would argue that basic executors support would have been a better addition to the standard. But the executors didn’t make it into the 2020 standard. So, let’s wait to see what the future will reserve us.

I also came across https://careers.coccoc.com/blogs/c-parallel-stl-is-not-yet-for-indiscriminate-use which looks like it covers much the same ground, but I haven't read it yet.

So, put C++ parallel algorithms in the "interesting, but not right now" pile!
 
> Managing data in Storage by `std::vector` or `thurst::vector` is planned. After finish the job, we can just drop `FillCpu()` and use `std::fill_n` instead.

Yes that is good - it should be possible to switch between back-ends at runtime, and they need to be able to manage their own storage.  Consider also the case of MPI-distributed calculations.  There are several ways to implement this, but one way would be to have  Storage type that references a block of data on a different MPI process.

**Comment by IvanaGyro** [comment]
I am interested in this optimization

```cpp
void FillReference(int* first, int count, const int& v) {
    // check and see if &v is outside the array.  If so, then optimize the loop
    if (&v < first || &v >= (first+count)) {
        FillValue(first, count, v);
    } else {  // slow path -- load v from memory
        for (int i = 0; i < count; ++i)
        {
            first[i] = v;
        }
    }
}
```

You mentioned that the compiler will not optimize the pass-by-reference version because other threads may change the assigned value while running the for-loop. If compilers consider this scenario, why the loop can be optimized with `-O3` enabled when the reference is not in the range?

**Comment by IvanaGyro** [comment]
C++ parallel algorithms are not powerful enough to make the program run on HPC or reach the best performance on every device, but C++ parallel algorithms are easy to use for vector-level parallelism and are equivalent to the use of OpenMP in the current code base. Shifting from OpenMP to C++ parallel algorithms doesn't limit us maybe until we fine-tune the chunk size passed to OpenMP. The benefit of using C++ parallel algorithms is that we can reduce one dependency when using Clang or MSVC, the latter is not supported now, as the compiler and can widely use STL algorithm functions. Of course, before discussing whether to switch to C++ parallel algorithms, we should check if parallelism is worth using in the current use cases.

**Comment by ianmccul** [comment]
> You mentioned that the compiler will not optimize the pass-by-reference version because other threads may change the assigned value while running the for-loop. If compilers consider this scenario, why the loop can be optimized with `-O3` enabled when the reference is not in the range?

That is a good question!  I think the answer is that the compiler can assume that the contents of some memory location will not change from underneath it (unless it is `volatile`, or there is some memory barrier ).  So my explanation of why the compiler is not doing that optimization was probably not correct -- the compiler is probably allowed to optimize `FillReference` in this particular case, but it does not.

So why not?  My guess is that it is an optimization that the compiler writers simply did not bother to add.  For -O3, the optimization to check first to see if the value is contained inside the array works much more generally, and also works in cases where the loop operation changes the value, such as the `add_value()` example.  For that function, with -O2, the generated code is
```assembly
.L12:
        mov     eax, DWORD PTR [rdx]
        add     DWORD PTR [rdi], eax
        add     rdi, 4
        cmp     rdi, rcx
        jne     .L12
```

With -O3, it does a test of the array bounds and runs the same code if the value is within the array, but if it is outside the array then it does a very optimized loop using 128-bit SSE registers (similar to the `fill` case).  This is a much more general, and useful, optimization that would benefit a lot of the algorithms in the STL, and it is quite possible that they add this optimization specifically because it happens so much in STL code.  The case (1) where the value is passed by reference, and also (2) the value is in the array, and also (3) but it happens that when it overwrites the value it does not change its value, is a very narrow corner-case that the compiler writers did not specifically optimize for.  There are many simple ways to get `fill()` to avoid reading from memory inside the loop anyway.  Even in generic code, if you know that there is a copy constructor, and you could make an extra local copy (which is probably not allowed in the STL!), and for some reason you wanted to pass by reference, you could write

```c++
template <typename T>
void FillReference(T* first, int count, const T& v) {
    T v_ = v;
    for (int i = 0; i < count; ++i)
    {
        first[i] = v_;
    }
}
```
and it is now using a local copy of `v`.

**Comment by IvanaGyro** [comment]
Regarding the optimization, I wrote a multi-thread program to inspect how GCC compiles the code when more than one thread is involved. It seems GCC only optimizes `FillReference` to `FillValue` when the value type is arithmetic or pointer. The behavior is the same as the `std::fill_n` implementation of GCC. As a result, implementing `Fill()` as `FillValue` is better as you mentioned until we support a larger type.
